dpkg-deb -Zgzip -b debs/spotty
dpkg-deb -Zgzip -b debs/bettertextselection
dpkg-deb -Zgzip -b debs/heartthrob
dpkg-deb -Zgzip -b debs/dontcorrectme
dpkg-deb -Zgzip -b debs/emojisuggest
dpkg-deb -Zgzip -b debs/messagefilteray
dpkg-deb -Zgzip -b debs/softtimer
dpkg-deb -Zgzip -b debs/predictionshortcuts
dpkg-deb -Zgzip -b debs/colorgrabber
dpkg-deb -Zgzip -b debs/onehanded
dpkg-deb -Zgzip -b debs/dejavu
dpkg-deb -Zgzip -b debs/tabcount
dpkg-deb -Zgzip -b debs/lesscontrol
dpkg-deb -Zgzip -b debs/airflip
dpkg-deb -Zgzip -b debs/divorce
dpkg-deb -Zgzip -b debs/shrinkray
dpkg-deb -Zgzip -b debs/thumbtack
dpkg-deb -Zgzip -b debs/albumpicker
dpkg-deb -Zgzip -b debs/protectdetails