dpkg-deb -Zgzip -b debs/spotty
dpkg-deb -Zgzip -b debs/bettertextselection
dpkg-deb -Zgzip -b debs/heartthrob
dpkg-deb -Zgzip -b debs/dontcorrectme
dpkg-deb -Zgzip -b debs/emojisuggest
dpkg-deb -Zgzip -b debs/messagefilter
dpkg-deb -Zgzip -b debs/softtimer
dpkg-deb -Zgzip -b debs/predictionshortcuts
dpkg-deb -Zgzip -b debs/colorgrabber
dpkg-deb -Zgzip -b debs/onehanded
dpkg-deb -Zgzip -b debs/softtimer9
dpkg-deb -Zgzip -b debs/dejavu